[PTT-94] Provision Frontend
pagopa/hub-pa-infra pull request #17
Opened 2021-05-03 07:48 UTC by GiovanniMancini

##Description
This PR proposes to add a module `frontend` based on a `blob storage` and a `cdn endpoint` to deploy a frontend based on static web files.

## Modules Added
- A module for a blob storage to deploy and serve static web files
- A module for a cdn endpoint
- A module `frontend` which can add a new blob storage configured to host static web content and the related cdn endpoint

## Resources added
- A new resource group
- A blob storage
- A cdn profile
- A cdn endpoint

## Status
Provisioned

2021-05-03 10:36 UTC, uolter requested changes

2021-05-03 10:36 UTC, uolter commented on modules/blob_storage/main.tf
> +  enabled            = true
Why do you enable by default the threat protection? Keep in mind it has "considerable" costs this setting.
Whether the storage contains static / public content might not need this additional property

2021-05-03 10:36 UTC, uolter commented on modules/blob_storage/main.tf
> +resource "azurerm_template_deployment" "versioning" {
As the advanced thread protection version has addition costs. I would not enable it by default.

2021-05-03 10:36 UTC, uolter commented on modules/cdn_endpoint/outputs.tf
> +  value = "${var.name}.azureedge.net"
```suggestion
  value = join(".", [var.name, "azureedge.net" ])
```

2021-05-03 10:36 UTC, uolter commented on outputs.tf
> +output "rg_frontend" {
Is this output resource group usefutl?

2021-05-04 18:12 UTC, GiovanniMancini commented on modules/blob_storage/main.tf
> +  enabled            = true
Ok I'll switch to false

2021-05-04 18:16 UTC, GiovanniMancini commented on outputs.tf
> +output "rg_frontend" {
I need it in `gitops` repo to configure deploy pipeline

2021-05-04 18:21 UTC, GiovanniMancini commented on modules/cdn_endpoint/outputs.tf
> +  value = "${var.name}.azureedge.net"
Fixed

2021-05-05 07:20 UTC, uolter approved these changes

2021-05-05 07:20 UTC, merged