[PTT-129] Add Identity to access key vault
pagopa/hub-pa-infra pull request #19
Opened 2021-05-05 06:47 UTC by GiovanniMancini

## Description
This PR proposes to add a certificate to support HTTPS at App Gateway level.

## Impacted resources
- App Gateway HTTP Listener
- Key Vault policy
- A new self signed certificate (useful just for testing purposes)
- A new user assigned identity to grant App Gateway read permissions on key vault

## Status
Can't apply due to permission issues

2021-05-05 07:05 UTC, uolter approved these changes

2021-05-06 05:45 UTC, uolter requested changes

2021-05-06 05:45 UTC, uolter commented on security.tf
> +resource "azurerm_key_vault_certificate" "app_gw_cert" {
We can not use a self signed certificate. At least in production.
Make it conditional or create a signed certificate with this script in an azure pipeline: https://github.com/pagopa/cert-az-management

2021-05-06 10:08 UTC, GiovanniMancini commented on security.tf
> +resource "azurerm_key_vault_certificate" "app_gw_cert" {
OK. @pasqualedevita this means that I have to create a new pipeline in `gitops` associated with the repository `hup-pa-infra` with write permission on Azure Subscrition. Do you agree? @uolter Does connection to letsencrypt require any secrets? I'm seeing that I have to set an email in `XXX_AcmeContact` .. should it came from a subscription to letsencrypt or it can be an arbitrary email?

2021-05-07 11:20 UTC, merged